### ISSUE TITLE
I have crafted some content but your settings are maybe not letting me merge them

### ISSUE THREAD

**Issue by RolletOso** [touhidalam69/SteemitResteemApplication#2]
I did a FAQ page and i have been trying to merge it ever since. Help me check it out.

**Comment by touhidalam69** [comment]
How you are trying to marge it...?
Please make Pull request, then i can marge it. Make sure your forked repository is updated.
[I have added FAQ from your forked Repository, but reverted. Please add some new points based on tag wise resteem]
[please follow the instruction](https://www.youtube.com/watch?v=yr6IzOGoMsQ)
thanks, for your contribution

**Comment by RolletOso** [comment]
Thank you very much. Followed the link to video and i have made a pull
request. Thanks

**Comment by touhidalam69** [comment]
Thanks for your contribution,
I have added those two...
